name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install system dependencies for Playwright
        run: |
          python -m pip install --upgrade pip
          pip install . '.[dev]'
          python -m playwright install --with-deps chromium
      - name: Lint (ruff)
        run: |
          python -m ruff check .
      - name: Tests
        run: |
          pytest -q
      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            artifacts/**
