name: Health Snapshot

on:
  workflow_dispatch:
    inputs:
      tweet_url:
        description: 'Tweet URL or ID to probe'
        required: false
      profile:
        description: 'Profile handle or URL to probe'
        required: false
      require:
        description: 'Required groups (compose,tweet,profile)'
        default: 'compose,tweet,profile'
        required: false
  schedule:
    - cron: '0 6 * * *'

jobs:
  snapshot:
    runs-on: ubuntu-latest
    env:
      XBOT_HEALTH_ENABLED: ${{ secrets.XBOT_HEALTH_ENABLED }}
      X_USER: ${{ secrets.X_USER }}
      X_PASSWORD: ${{ secrets.X_PASSWORD }}
      X_EMAIL: ${{ secrets.X_EMAIL }}
      X_HANDLE: ${{ secrets.X_HANDLE }}
      PROXY_URL: ${{ secrets.PROXY_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel setuptools
          pip install -e .[dev]
          python -m playwright install chromium
          python -m playwright install-deps || true
      - name: Selectors snapshot (requires secrets)
        if: env.XBOT_HEALTH_ENABLED == 'true'
        run: |
          json_out="Docs/status/selectors_snapshot_${{ github.run_id }}.json"
          python -m xbot.cli health snapshot \
            --require "${{ github.event.inputs.require || 'compose,tweet,profile' }}" \
            --json-out "$json_out" \
            ${ { github.event.inputs.tweet_url && format('--tweet-url {0}', github.event.inputs.tweet_url) } } \
            ${ { github.event.inputs.profile && format('--profile {0}', github.event.inputs.profile) } }
          echo "Wrote $json_out"
      - name: Upload Docs/status
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-status
          path: Docs/status

